### ISSUE TITLE
PHPUnit: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by Kubitomakita** [gerardroche/sublime-phpunit#66]
Hi,

this is the issue I get when I try to run any test:
`PHPUnit: 'NoneType' object has no attribute 'items'`

**Comment by gerardroche** [comment]
I think you have the `phpunit.options` setting set to an invalid type e.g. `null`. I've pushed a change that provides better error handling. The console log is at `Menu > View > Show Console`.

It should be a valid `dict`, for no options set it to `{}` or with valid PHPUnit options:

Set it globally: `Preferences > Settings`

```json
{
	"phpunit.options": {
		"no-coverage": true
	}
}
```

Or per-project: `Project > Edit Project`

```json
{
    "settings": {
        "phpunit.options": {}
    }
}
```

**Comment by Kubitomakita** [comment]
Turned out that it works after machine reboot...

phpunit.options was just empty object provided by the default config file. I didn't configure anything, just installed via Package Control and tried to use it.

**Comment by gerardroche** [comment]
Thanks. I added much better error handling. If this occurs again please take a look at the console log, `Menu > View > Show Console`, and post the exception traceback to help debugging the issue. Looks like it's a edge case issue

**Comment by aabdyli** [comment]
OS: Win 7 SP1
ST: v3 3142
Exeption:
PHPUnit: ''NoneType' object has no attribute 'items''
Traceback (most recent call last):
  File "C:\Users\User\My Apps\Sublime Text\sublime_plugin.py", line 797, in run_
    return self.run()
  File "plugin in C:\Users\User\My Apps\Sublime Text\Data\Installed Packages\phpunitkit.sublime-package", line 511, in run
  File "plugin in C:\Users\User\My Apps\Sublime Text\Data\Installed Packages\phpunitkit.sublime-package", line 361, in run
  File "plugin in C:\Users\User\My Apps\Sublime Text\Data\Installed Packages\phpunitkit.sublime-package", line 341, in run
  File "plugin in C:\Users\User\My Apps\Sublime Text\Data\Installed Packages\phpunitkit.sublime-package", line 451, in filter_options
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by aabdyli** [comment]
Everything works correctly out of the box with the new release.
Thanks for the quick support.
